/**
 * To simplify things and avoid writing a mapper between the representation of the SWAPI and
 * our representation, all properties are just strings and the case used is the same as the
 * one from the API. Besides, some unneeded fields are ignored such as created or edited.
 */
 export interface Pilot {
  id: number; // generated by DataService, independent from SWAPI's id

  name: string;
  height: string;
  mass: string;
  hair_color: string;
  skin_color: string;
  eye_color: string;
  birth_year: string;
  gender: string;

  homeworld: string;
  films: string[];
  species: string[];
  vehicles: string[];
  starships: string[];

  url: string;
}
