import { Pilot } from "./Pilot";

/**
 * To simplify things and avoid writing a mapper between the representation of the SWAPI and
 * our representation, all properties are just strings and the case used is the same as the
 * one from the API. Besides, some unneeded fields are ignored such as created or edited.
 */
export interface Starship {
  id: number; // generated by DataService, independent from SWAPI's id

  name: string;
  model: string;
  manufacturer: string;
  cost_in_credits: string;
  length: string;
  max_atmosphering_speed: string;
  crew: string;
  passengers: string;
  cargo_capacity: string;
  consumables: string;
  hyperdrive_rating: string;
  MGLT: string;
  starship_class: string;

  pilots: string[]; // list of pilot URLs
  films: string[]; // list of film URLs

  pilotsData: Pilot[]; // list of actual pilot data
}
